version: "3.7"

services:
  realtime-whisper:
    build: .
    ports:
      - 8760:8760
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [utility, compute]
