version: "3.7"

volumes:
  model-cache: {}


services:
  realtime-whisper:
    build:
      context: .
    ports:
      - 8760:8760
      - 7860:7860
    volumes:
      - model-cache:/root/.cache/huggingface
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [utility, compute]
